export const configPresets = [
    {
      id: 'dodgehigh',
      displayName: 'Dodge\'s High Graphics',
      author: 'Dodge',
      description: 'Nice looking, high graphics ini.'
    },
    {
      id: 'evil',
      displayName: 'Evil\'s Ini',
      author: 'Evil',
      description: 'Good for spotting. Based on Sheepi\'s ini.'
    },
    {
      id: 'evillow',
      displayName: 'Evil\'s Low Graphics',
      author: 'Evil',
      description: 'Balanced beween visability, and good performance.'
    },
    {
      id: 'veryhigh',
      displayName: 'Very High Graphics',
      author: 'Sorwis',
      description: 'Max graphics, beyond in game settings.'
    },
    {
      id: 'verylow',
      displayName: 'Minecraft Graphics',
      author: 'N/A',
      description: 'Minimum settings, best if you have a weak PC.'
    },
    {
      id: 'defaultini',
      displayName: 'Hirez Default',
      author: 'Hirez',
      description: 'Default ini generated by the game, with a few fixes.'
    }
  ];